export const DSA_TOPICS = [
  { name: "Sorting", total: 5 },
  { name: "Arrays", total: 31 },
  { name: "Linked Lists", total: 45 },
  { name: "Binary Search", total: 28 },
  { name: "Hashing", total: 4 },
  { name: "Recursion", total: 17 },
  { name: "Greedy Algorithms", total: 11 },
  { name: "Sliding Window", total: 11 },
  { name: "Stack/Queues", total: 23 },
  { name: "Binary Trees", total: 30 },
  { name: "Binary Search Trees", total: 14 },
  { name: "Heaps", total: 10 },
  { name: "Graphs", total: 36 },
  { name: "Tries", total: 6 },
  { name: "Dynamic Programming", total: 47 },
  { name: "Strings (Advanced Algo)", total: 8 },
  { name: "Maths", total: 3 },
  { name: "Bit Manipulation", total: 8 },
]
